from .search import search
from .weather_data import weather_data
from .government_scheme_data import government_scheme_data
from .all_government_schemes import all_government_schemes
from .plant_information import plant_information
from .crop_calendar import crop_calendar
from .mandi_prices import mandi_prices
from .fertilizer_calculator import fertilizer_dosage_calculator
from .seed_calculator import seed_requirement_calculator
from .irrigation_calculator import irrigation_calculator
from .pesticide_calculator import pesticide_dilution_calculator
from .profitability_calculator import profitability_calculator

tools = [search, weather_data, government_scheme_data, all_government_schemes, plant_information, crop_calendar, mandi_prices, fertilizer_dosage_calculator, seed_requirement_calculator, irrigation_calculator, pesticide_dilution_calculator, profitability_calculator]